Repository Miso-Code/sportapp-front, pull requests merged in 2024-04, with the labels that each got.

#5 Feature: PSA-156 create initial packages
  .gitignore
  .lintstagedrc.json
  packages/eslint-config/custom-library.js
  packages/langs/en.json
  packages/langs/en/en.json
  packages/langs/en/errors.json
  packages/langs/en/form.json
  packages/langs/en/index.js
  packages/langs/en/register.json
  packages/langs/en/validations.json
  packages/langs/es.json
  packages/langs/es/errors.json
  packages/langs/es/es.json
  packages/langs/es/form.json
  packages/langs/es/index.js
  packages/langs/es/register.json
  packages/langs/es/validations.json
  packages/langs/package.json
  packages/stores/.eslintrc.cjs
  packages/stores/.gitignore
  packages/stores/.prettierrc.js
  packages/stores/jest.config.ts
  packages/stores/package.json
  packages/stores/src/__tests__/index.spec.ts
  packages/stores/src/auth/__tests__/index.spec.ts
  packages/stores/src/auth/index.ts
  packages/stores/src/auth/interfaces/index.ts
  packages/stores/src/index.ts
  packages/stores/tsconfig.json
  turbo.json
  yarn.lock
Labels: feature

#7 Feature: PSA-156 add components and containers
  apps/web/config/lang/form.ts
  apps/web/config/lang/i18n.ts
  apps/web/config/test/jest.setup.ts
  apps/web/jest.config.ts
  apps/web/package.json
  apps/web/src/assets/images/login-wallpaper.jpg
  apps/web/src/components/Inputs/DatePickerController/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/components/Inputs/DatePickerController/__tests__/index.spec.tsx
  apps/web/src/components/Inputs/DatePickerController/index.tsx
  apps/web/src/components/Inputs/DatePickerController/interfaces/index.ts
  apps/web/src/components/Inputs/SelectController/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/components/Inputs/SelectController/__tests__/index.spec.tsx
  apps/web/src/components/Inputs/SelectController/index.tsx
  apps/web/src/components/Inputs/SelectController/interfaces/index.ts
  apps/web/src/components/Inputs/TexFieldController/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/components/Inputs/TexFieldController/__tests__/index.spec.tsx
  apps/web/src/components/Inputs/TexFieldController/index.tsx
  apps/web/src/components/Inputs/TexFieldController/interfaces/index.ts
  apps/web/src/components/Inputs/TexFieldPasswordController/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/components/Inputs/TexFieldPasswordController/__tests__/index.spec.tsx
  apps/web/src/components/Inputs/TexFieldPasswordController/index.tsx
  apps/web/src/components/Inputs/TexFieldPasswordController/interfaces/index.ts
  apps/web/src/components/SecondarySection/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/components/SecondarySection/__tests__/index.spec.tsx
  apps/web/src/components/SecondarySection/_index.scss
  apps/web/src/components/SecondarySection/index.tsx
  apps/web/src/components/SecondarySection/interfaces/index.ts
  apps/web/src/components/TransitionAlert/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/components/TransitionAlert/__tests__/index.spec.tsx
  apps/web/src/components/TransitionAlert/index.tsx
  apps/web/src/components/TransitionAlert/interfaces/index.ts
  apps/web/src/containers/Register/Default/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/containers/Register/Default/__tests__/index.spec.tsx
  apps/web/src/containers/Register/Default/_index.scss
  apps/web/src/containers/Register/Default/index.tsx
  apps/web/src/containers/Register/Default/utils/__tests__/index.spec.tsx
  apps/web/src/containers/Register/Default/utils/schema.ts
  apps/web/src/containers/Register/Full/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/containers/Register/Full/__tests__/index.spec.tsx
  apps/web/src/containers/Register/Full/_index.scss
  apps/web/src/containers/Register/Full/index.tsx
  apps/web/src/containers/Register/Full/utils/schema.ts
  apps/web/src/containers/Register/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/containers/Register/__tests__/index.spec.tsx
  apps/web/src/containers/Register/index.tsx
  apps/web/src/containers/Register/interfaces/index.ts
  apps/web/src/pages/Home/__tests__/index.spec.tsx
  apps/web/src/pages/Home/_index.scss
  apps/web/src/router/index.tsx
  apps/web/src/utils/__tests__/index.spec.ts
  apps/web/src/utils/countries.ts
  apps/web/tsconfig.json
  apps/web/vite.config.ts
  yarn.lock
Labels: feature

#8 Feature: PSA-156 Add register page in web app
  apps/web/src/main.tsx
  apps/web/src/pages/Register/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/Register/__tests__/index.spec.tsx
  apps/web/src/pages/Register/_index.scss
  apps/web/src/pages/Register/index.tsx
  apps/web/src/router/__tests__/index.spec.tsx
  apps/web/src/router/index.tsx
  apps/web/src/router/private/Layout/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/router/private/Layout/__tests__/index.spec.tsx
  apps/web/src/router/private/Layout/index.tsx
  apps/web/src/router/private/__tests__/index.spec.tsx
  apps/web/src/router/private/routes.tsx
  apps/web/src/router/public/__tests__/index.spec.tsx
  apps/web/src/router/public/routes.tsx
Labels: feature

#9 Feat: PSA-156 update login button and delete consoles
  apps/web/src/containers/Register/Default/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/containers/Register/Default/index.tsx
  apps/web/src/containers/Register/Full/index.tsx
  apps/web/src/containers/Register/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/Register/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/Register/index.tsx
  packages/langs/en/register.json
  packages/langs/es/register.json
Labels: feature

#11 Refactor: PSA-156 update global-varibales
  apps/web/jest.config.ts
  apps/web/vite.config.ts
  packages/sportapp-repository/src/index.ts
  packages/sportapp-repository/src/user/__tests__/index.spec.ts
  packages/sportapp-repository/src/user/index.ts
  packages/sportapp-repository/src/utils/global-variables/__tests__/index.spec.ts
  packages/sportapp-repository/src/utils/global-variables/index.ts
  turbo.json
Labels: refactor

#12 Feature: PSA-158 add login container and login translate
  apps/web/package.json
  apps/web/src/containers/Login/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/containers/Login/__tests__/index.spec.tsx
  apps/web/src/containers/Login/_index.scss
  apps/web/src/containers/Login/index.tsx
  apps/web/src/containers/Login/interfaces/index.ts
  apps/web/src/containers/Login/utils/schema.ts
  packages/langs/en/index.ts
  packages/langs/en/login.json
  packages/langs/es/index.ts
  packages/langs/es/login.json
  yarn.lock
Labels: feature

#13 Feature: PSA-158 add login page
  apps/web/src/components/Inputs/DatePickerController/index.tsx
  apps/web/src/components/Inputs/DatePickerController/interfaces/index.ts
  apps/web/src/components/Inputs/SelectController/index.tsx
  apps/web/src/components/Inputs/SelectController/interfaces/index.ts
  apps/web/src/components/Inputs/TexFieldController/index.tsx
  apps/web/src/components/Inputs/TexFieldController/interfaces/index.ts
  apps/web/src/components/Inputs/TexFieldPasswordController/index.tsx
  apps/web/src/components/Inputs/TexFieldPasswordController/interfaces/index.ts
  apps/web/src/components/SecondarySection/interfaces/index.ts
  apps/web/src/pages/Login/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/Login/__tests__/index.spec.tsx
  apps/web/src/pages/Login/_index.scss
  apps/web/src/pages/Login/index.tsx
  apps/web/src/router/private/Layout/index.tsx
  apps/web/src/router/private/__tests__/index.spec.tsx
  apps/web/src/router/private/routes.tsx
  apps/web/src/router/public/Layout/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/router/public/Layout/__tests__/index.spec.tsx
  apps/web/src/router/public/Layout/index.tsx
  apps/web/src/router/public/Layout/interfaces/index.ts
  apps/web/src/router/public/routes.tsx
  apps/web/vite.config.ts
Labels: feature

#14 Feature: PSA-158 update store
  apps/mobile/src/app/__tests__/index.spec.tsx
  apps/web/src/containers/Register/Full/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/containers/Register/Full/index.tsx
  apps/web/src/containers/Register/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/containers/Register/interfaces/index.ts
  apps/web/src/pages/Login/__tests__/index.spec.tsx
  apps/web/src/pages/Login/index.tsx
  apps/web/src/pages/Register/__tests__/index.spec.tsx
  apps/web/src/pages/Register/index.tsx
  packages/stores/package.json
  packages/stores/src/auth/index.ts
  packages/stores/src/utils/__tests__/index.spec.ts
  packages/stores/src/utils/storages.ts
  turbo.json
  yarn.lock
Labels: feature

#15 Bugfix: PSA-158 correction register schema
  apps/web/src/containers/Register/Full/utils/schema.ts
  packages/stores/src/auth/index.ts
Labels: bugfix

#16 Feature: PAS-169 create navbar and profile menu
  apps/web/src/components/ContainerLayout/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/components/ContainerLayout/__tests__/index.spec.tsx
  apps/web/src/components/ContainerLayout/_index.scss
  apps/web/src/components/ContainerLayout/index.tsx
  apps/web/src/components/ContainerLayout/interfaces/index.tsx
  apps/web/src/components/Navbar/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/components/Navbar/__tests__/index.spec.tsx
  apps/web/src/components/Navbar/_index.scss
  apps/web/src/components/Navbar/index.tsx
  apps/web/src/components/Navbar/interfaces/index.ts
  apps/web/src/pages/Login/index.tsx
  apps/web/src/pages/Register/index.tsx
  packages/langs/en/index.ts
  packages/langs/en/navbar.json
  packages/langs/en/profile.json
  packages/langs/es/index.ts
  packages/langs/es/navbar.json
  packages/langs/es/profile.json
Labels: feature

#17 Feature: PSA-169 create menu profile
  apps/web/src/pages/Home/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/Home/_index.scss
  apps/web/src/pages/Home/components/Menu/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/Home/components/Menu/__tests__/index.spec.tsx
  apps/web/src/pages/Home/components/Menu/_index.scss
  apps/web/src/pages/Home/components/Menu/index.tsx
  apps/web/src/pages/Home/components/Menu/interfaces/index.ts
  apps/web/src/pages/Home/index.tsx
Labels: feature

#18 Feature: PSA-169 add personalDataContainer
  apps/web/src/components/ContainerLayout/_index.scss
  apps/web/src/components/Inputs/DatePickerController/index.tsx
  apps/web/src/components/Inputs/DatePickerController/interfaces/index.ts
  apps/web/src/components/Navbar/_index.scss
  apps/web/src/containers/PersonalDataForm/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/containers/PersonalDataForm/__tests__/index.spec.tsx
  apps/web/src/containers/PersonalDataForm/_index.scss
  apps/web/src/containers/PersonalDataForm/index.tsx
  apps/web/src/containers/PersonalDataForm/interfaces/index.ts
  apps/web/src/containers/PersonalDataForm/utils/schema.ts
Labels: feature

#20 Feature: PSA-171 create sport data form
  apps/web/src/containers/SportDataForm/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/containers/SportDataForm/__tests__/index.spec.tsx
  apps/web/src/containers/SportDataForm/_index.scss
  apps/web/src/containers/SportDataForm/index.tsx
  apps/web/src/containers/SportDataForm/interfaces/index.ts
  apps/web/src/containers/SportDataForm/utils/schema.ts
Labels: feature

#21 Feeature: PSA-171 create select multi and update sportdataform
  apps/web/src/components/Inputs/SelectController/index.tsx
  apps/web/src/components/Inputs/SelectMulti/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/components/Inputs/SelectMulti/__tests__/index.spec.tsx
  apps/web/src/components/Inputs/SelectMulti/index.tsx
  apps/web/src/components/Inputs/SelectMulti/interfaces/index.ts
  apps/web/src/containers/SportDataForm/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/containers/SportDataForm/index.tsx
  apps/web/src/containers/SportDataForm/utils/schema.ts
Labels: feature

#22 Feature: PSA-171 create menu from home
  apps/web/src/pages/Home/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/Home/components/Menu/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/Home/components/Menu/__tests__/index.spec.tsx
  apps/web/src/pages/Home/components/Menu/_index.scss
  apps/web/src/pages/Home/components/Menu/index.tsx
  apps/web/src/pages/Home/components/Menu/interfaces/index.ts
Labels: feature

#24 Feature: PSA-171 add translate in profiles forms
  apps/web/src/containers/SportDataForm/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/containers/SportDataForm/index.tsx
  packages/langs/en/form.json
  packages/langs/en/index.ts
  packages/langs/en/nutritionalDataForm.json
  packages/langs/en/personalDataForm.json
  packages/langs/en/sportDataForm.json
  packages/langs/es/form.json
  packages/langs/es/index.ts
  packages/langs/es/nutritionalDataForm.json
  packages/langs/es/personalDataForm.json
  packages/langs/es/sportDataForm.json
Labels: feature

#25 Feature: PSA-1712 create radio button controller
  apps/web/src/components/Inputs/RadioButtonController/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/components/Inputs/RadioButtonController/__tests__/index.spec.tsx
  apps/web/src/components/Inputs/RadioButtonController/index.tsx
  apps/web/src/components/Inputs/RadioButtonController/interfaces/index.ts
Labels: feature

#27 Feature: PSA-172 create nutritional data form
  apps/web/src/containers/NutritionalDataForm/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/containers/NutritionalDataForm/__tests__/index.spec.tsx
  apps/web/src/containers/NutritionalDataForm/_index.scss
  apps/web/src/containers/NutritionalDataForm/index.tsx
  apps/web/src/containers/NutritionalDataForm/interfaces/index.ts
  apps/web/src/containers/NutritionalDataForm/utils/schema.ts
Labels: feature

#28 Feature: PSA-172 add translate from nutritional data form
  packages/langs/en/form.json
  packages/langs/es/form.json
Labels: feature

#29 Feature: PSA-172 add profilemenu in home page
  apps/web/src/components/Inputs/SelectMulti/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/components/Inputs/SelectMulti/index.tsx
  apps/web/src/containers/NutritionalDataForm/index.tsx
  apps/web/src/containers/SportDataForm/index.tsx
  apps/web/src/pages/Home/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/Home/__tests__/index.spec.tsx
  apps/web/src/pages/Home/_index.scss
  apps/web/src/pages/Home/components/Menu/utils/__tests__/index.spec.ts
  apps/web/src/pages/Home/components/Menu/utils/index.ts
  apps/web/src/pages/Home/index.tsx
Labels: bugfix, feature

#31 Feature: PSA-169 update storage to get and update profile data
  packages/sportapp-repository/src/user/__tests__/index.spec.ts
  packages/sportapp-repository/src/user/endpoints/__tests__/index.spec.ts
  packages/sportapp-repository/src/user/endpoints/index.ts
  packages/sportapp-repository/src/user/index.ts
  packages/sportapp-repository/src/user/interfaces/api/personalProfile.ts
  packages/stores/src/user/__tests__/index.spec.ts
  packages/stores/src/user/index.ts
  packages/stores/src/user/interfaces/index.ts
Labels: feature

#32 Feature: PSA-169 add get and update personal data from storage
  apps/web/src/components/Inputs/DatePickerController/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/components/Inputs/DatePickerController/__tests__/index.spec.tsx
  apps/web/src/components/Inputs/DatePickerController/index.tsx
  apps/web/src/containers/PersonalDataForm/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/containers/PersonalDataForm/index.tsx
  apps/web/src/containers/PersonalDataForm/utils/schema.ts
  apps/web/src/pages/Home/__tests__/index.spec.tsx
  apps/web/src/pages/Home/index.tsx
  apps/web/src/utils/countries.ts
  packages/stores/src/auth/index.ts
Labels: feature

#33 Feature: PSA-171 add get sport data and update sport data
  packages/sportapp-repository/src/user/__tests__/index.spec.ts
  packages/sportapp-repository/src/user/index.ts
  packages/sportapp-repository/src/user/interfaces/api/sportProfile.ts
  packages/stores/src/user/__tests__/index.spec.ts
  packages/stores/src/user/index.ts
  packages/stores/src/user/interfaces/index.ts
Labels: feature

#35 Feature: PSA-171 update style in web app page
  apps/web/postcss.config.js
  apps/web/src/main.tsx
  apps/web/tailwind.config.js
Labels: feature

#36 Feature: PSA-171 update styles
  apps/web/src/components/ContainerLayout/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/components/ContainerLayout/index.tsx
  apps/web/src/components/SecondarySection/_index.scss
  apps/web/src/index.scss
  apps/web/src/pages/Home/__tests__/__snapshots__/index.spec.tsx.snap
Labels: feature

#38 Feature: Add workflow to sync sonar coverage on branches (develop and main)
  .github/workflows/check-pr-mobile.yml
  .github/workflows/sync-sonar-coverage.yml
Labels: feature

#37 Feature: PSA-176 View sport session history list
  apps/mobile/package.json
  apps/mobile/src/app/(main)/(tabs)/training/__tests__/__snapshots__/_layout.spec.tsx.snap
  apps/mobile/src/app/(main)/(tabs)/training/__tests__/__snapshots__/sportSessionHistory.spec.tsx.snap
  apps/mobile/src/app/(main)/(tabs)/training/__tests__/_layout.spec.tsx
  apps/mobile/src/app/(main)/(tabs)/training/__tests__/sportSessionHistory.spec.tsx
  apps/mobile/src/app/(main)/(tabs)/training/_layout.tsx
  apps/mobile/src/app/(main)/(tabs)/training/index.tsx
  apps/mobile/src/app/(main)/(tabs)/training/sportSessionHistory.tsx
  apps/mobile/src/components/Header.tsx
  apps/mobile/src/components/Kpi.tsx
  apps/mobile/src/components/TrainingCard.tsx
  apps/mobile/src/components/__tests__/Header.spec.tsx
  apps/mobile/src/components/__tests__/TrainingCard.spec.tsx
  apps/mobile/src/components/__tests__/__snapshots__/Header.spec.tsx.snap
  apps/mobile/src/components/__tests__/__snapshots__/TrainingCard.spec.tsx.snap
  apps/mobile/src/config/test/__mocks__/dayjs/index.ts
  apps/mobile/src/config/test/__mocks__/dayjs/locale/en.ts
  apps/mobile/src/config/test/__mocks__/dayjs/locale/es.ts
  apps/mobile/src/config/theme.ts
  packages/langs/en/training.json
  packages/langs/es/training.json
  packages/sportapp-repository/src/sportSession/__tests__/index.spec.ts
  packages/sportapp-repository/src/sportSession/endpoints/index.ts
  packages/sportapp-repository/src/sportSession/index.ts
  packages/stores/src/sportSession/__tests__/index.spec.ts
  packages/stores/src/sportSession/index.ts
  packages/stores/src/sportSession/interfaces/index.ts
  yarn.lock
Labels: feature

#40 Feature: PSA-173 update stores, repository and translates
  apps/mobile/src/app/(main)/(tabs)/training/__tests__/index.spec.tsx
  apps/mobile/src/app/(main)/(tabs)/training/__tests__/sportSessionHistory.spec.tsx
  apps/mobile/src/app/(main)/(tabs)/training/__tests__/sportSessionSummary.spec.tsx
  apps/mobile/src/app/(main)/(tabs)/training/sportSessionHistory.tsx
  apps/mobile/src/app/(main)/(tabs)/training/sportSessionSummary.tsx
  apps/mobile/src/hooks/useLocation.ts
  apps/web/src/pages/Home/index.tsx
  packages/langs/en/en.json
  packages/langs/en/errors.json
  packages/langs/es/errors.json
  packages/langs/es/es.json
  packages/sportapp-repository/src/sport/endpoints/index.ts
  packages/sportapp-repository/src/sport/index.ts
  packages/sportapp-repository/src/sportSession/endpoints/index.ts
  packages/sportapp-repository/src/sportSession/index.ts
  packages/sportapp-repository/src/sportSession/interfaces/index.ts
  packages/sportapp-repository/src/user/__tests__/index.spec.ts
  packages/sportapp-repository/src/user/endpoints/__tests__/index.spec.ts
  packages/sportapp-repository/src/user/endpoints/index.ts
  packages/sportapp-repository/src/user/index.ts
  packages/sportapp-repository/src/user/interfaces/api/nutritionalProfile.ts
  packages/sportapp-repository/src/user/interfaces/api/sportProfile.ts
  packages/sportapp-repository/src/user/interfaces/index.ts
  packages/stores/src/auth/__tests__/index.spec.ts
  packages/stores/src/auth/index.ts
  packages/stores/src/sport/index.ts
  packages/stores/src/sportSession/__tests__/index.spec.ts
  packages/stores/src/sportSession/index.ts
  packages/stores/src/user/__tests__/index.spec.ts
  packages/stores/src/user/index.ts
  packages/stores/src/user/interfaces/index.ts
Labels: refactor, feature

#41 Feature: PSA-174 add sport data form and nutricional data form connections
  apps/web/index.html
  apps/web/public/robots.txt
  apps/web/src/components/Inputs/DatePickerController/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/components/Inputs/DatePickerController/__tests__/index.spec.tsx
  apps/web/src/components/Inputs/DatePickerController/index.tsx
  apps/web/src/components/Inputs/DatePickerController/interfaces/index.ts
  apps/web/src/containers/NutritionalDataForm/__tests__/index.spec.tsx
  apps/web/src/containers/NutritionalDataForm/index.tsx
  apps/web/src/containers/NutritionalDataForm/utils/schema.ts
  apps/web/src/containers/PersonalDataForm/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/containers/PersonalDataForm/_index.scss
  apps/web/src/containers/PersonalDataForm/index.tsx
  apps/web/src/containers/Register/Full/index.tsx
  apps/web/src/containers/Register/Full/utils/schema.ts
  apps/web/src/containers/SportDataForm/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/containers/SportDataForm/index.tsx
  apps/web/src/containers/SportDataForm/utils/schema.ts
  apps/web/src/pages/Home/__tests__/index.spec.tsx
  apps/web/src/pages/Home/index.tsx
  apps/web/src/pages/Login/__tests__/index.spec.tsx
  apps/web/src/pages/Login/index.tsx
  apps/web/src/pages/Register/__tests__/index.spec.tsx
  apps/web/src/pages/Register/index.tsx
  apps/web/src/router/index.tsx
  packages/langs/en/form.json
  packages/langs/en/nutritionalDataForm.json
  packages/langs/es/form.json
  packages/langs/es/nutritionalDataForm.json
  packages/sportapp-repository/src/user/interfaces/api/sportProfile.ts
  packages/stores/src/user/interfaces/index.ts
Labels: refactor, feature

#42 Bugfix: PSA-174 correction langs and styles
  apps/web/src/containers/NutritionalDataForm/_index.scss
  apps/web/src/containers/PersonalDataForm/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/containers/PersonalDataForm/__tests__/index.spec.tsx
  packages/langs/es/nutritionalDataForm.json
  packages/langs/es/profile.json
Labels: bugfix

#46 Feature: PSA-174 corrections
  apps/web/src/components/Inputs/TexFieldController/index.tsx
  apps/web/src/containers/NutritionalDataForm/index.tsx
  apps/web/src/containers/PersonalDataForm/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/containers/PersonalDataForm/index.tsx
  apps/web/src/containers/Register/Full/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/containers/Register/Full/index.tsx
  apps/web/src/containers/Register/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/containers/SportDataForm/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/containers/SportDataForm/index.tsx
  apps/web/src/main.tsx
  apps/web/src/pages/Home/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/Home/components/Menu/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/Home/components/Menu/index.tsx
  apps/web/src/pages/Home/index.tsx
  apps/web/src/pages/Login/index.tsx
  apps/web/src/pages/Register/index.tsx
  packages/langs/en/form.json
  packages/langs/es/form.json
Labels: bugfix

#48 BugFix: demo request
  packages/langs/es/profile.json
Labels: bugfix

#49 Feature: PSA-181 add configuration view
  apps/web/config/test/jest.setup.ts
  apps/web/src/components/Navbar/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/components/Navbar/__tests__/index.spec.tsx
  apps/web/src/components/Navbar/index.tsx
  apps/web/src/components/Navbar/interfaces/index.ts
  apps/web/src/components/Spinner/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/components/Spinner/__tests__/index.spec.tsx
  apps/web/src/components/Spinner/_index.scss
  apps/web/src/components/Spinner/index.tsx
  apps/web/src/components/Spinner/interfaces/index.ts
  apps/web/src/pages/Config/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/Config/__tests__/index.spec.tsx
  apps/web/src/pages/Config/_index.scss
  apps/web/src/pages/Config/components/Menu/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/Config/components/Menu/__tests__/index.spec.tsx
  apps/web/src/pages/Config/components/Menu/_index.scss
  apps/web/src/pages/Config/components/Menu/index.tsx
  apps/web/src/pages/Config/components/Menu/interfaces/index.ts
  apps/web/src/pages/Config/index.tsx
  apps/web/src/router/private/Layout/index.tsx
  apps/web/src/router/private/lazy-pages/index.ts
  apps/web/src/router/private/routes.tsx
  apps/web/src/router/public/Layout/index.tsx
  apps/web/src/router/public/lazy-pages/index.ts
  apps/web/src/router/public/routes.tsx
  packages/langs/en/config.json
  packages/langs/en/index.ts
  packages/langs/es/config.json
  packages/langs/es/index.ts
Labels: refactor, feature

#50 Feature: PSA-181 add partner register page
  apps/web/src/containers/Partner/Register/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/containers/Partner/Register/__tests__/index.spec.tsx
  apps/web/src/containers/Partner/Register/_index.scss
  apps/web/src/containers/Partner/Register/index.tsx
  apps/web/src/containers/Partner/Register/interfaces/index.ts
  apps/web/src/containers/Partner/Register/utils/__tests__/index.spec.tsx
  apps/web/src/containers/Partner/Register/utils/schema.ts
  apps/web/src/pages/Partner/Register/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/Partner/Register/__tests__/index.spec.tsx
  apps/web/src/pages/Partner/Register/_index.scss
  apps/web/src/pages/Partner/Register/index.tsx
  apps/web/src/pages/User/Config/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/User/Config/__tests__/index.spec.tsx
  apps/web/src/pages/User/Config/_index.scss
  apps/web/src/pages/User/Config/components/Menu/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/User/Config/components/Menu/__tests__/index.spec.tsx
  apps/web/src/pages/User/Config/components/Menu/_index.scss
  apps/web/src/pages/User/Config/components/Menu/index.tsx
  apps/web/src/pages/User/Config/components/Menu/interfaces/index.ts
  apps/web/src/pages/User/Config/index.tsx
  apps/web/src/pages/User/Home/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/User/Home/__tests__/index.spec.tsx
  apps/web/src/pages/User/Home/_index.scss
  apps/web/src/pages/User/Home/components/Menu/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/User/Home/components/Menu/__tests__/index.spec.tsx
  apps/web/src/pages/User/Home/components/Menu/_index.scss
  apps/web/src/pages/User/Home/components/Menu/index.tsx
  apps/web/src/pages/User/Home/components/Menu/interfaces/index.ts
  apps/web/src/pages/User/Home/components/Menu/utils/__tests__/index.spec.ts
  apps/web/src/pages/User/Home/components/Menu/utils/index.ts
  apps/web/src/pages/User/Home/index.tsx
  apps/web/src/pages/User/Login/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/User/Login/__tests__/index.spec.tsx
  apps/web/src/pages/User/Login/_index.scss
  apps/web/src/pages/User/Login/index.tsx
  apps/web/src/pages/User/Register/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/User/Register/__tests__/index.spec.tsx
  apps/web/src/pages/User/Register/_index.scss
  apps/web/src/pages/User/Register/index.tsx
  apps/web/src/router/private/lazy-pages/index.ts
  apps/web/src/router/public/__tests__/index.spec.tsx
  apps/web/src/router/public/lazy-pages/index.ts
  apps/web/src/router/public/routes.tsx
  packages/langs/en/form.json
  packages/langs/en/login.json
  packages/langs/en/register.json
  packages/langs/es/form.json
  packages/langs/es/login.json
  packages/langs/es/register.json
  packages/sportapp-repository/src/business-partner/__tests__/index.spec.ts
  packages/sportapp-repository/src/business-partner/endpoints/__tests__/index.spec.ts
  packages/sportapp-repository/src/business-partner/endpoints/index.ts
  packages/sportapp-repository/src/business-partner/index.ts
  packages/sportapp-repository/src/business-partner/interfaces/api/login.ts
  packages/sportapp-repository/src/business-partner/interfaces/api/register.ts
  packages/stores/src/index.ts
  packages/stores/src/partner/auth/__tests__/index.spec.ts
  packages/stores/src/partner/auth/index.ts
  packages/stores/src/partner/auth/interfaces/index.ts
Labels: refactor, feature

#53 Feature: PSA-185 create navbar top
  apps/web/src/components/NavbarTop/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/components/NavbarTop/__tests__/index.spec.tsx
  apps/web/src/components/NavbarTop/index.tsx
  apps/web/src/pages/Partner/CreateProduct/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/Partner/CreateProduct/__tests__/index.spec.tsx
  apps/web/src/pages/Partner/CreateProduct/index.tsx
  apps/web/src/pages/Partner/Home/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/Partner/Home/__tests__/index.spec.tsx
  apps/web/src/pages/Partner/Home/index.tsx
  apps/web/src/pages/Partner/PurchasedProduct/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/Partner/PurchasedProduct/__tests__/index.spec.tsx
  apps/web/src/pages/Partner/PurchasedProduct/index.tsx
  apps/web/src/pages/User/Login/index.tsx
  apps/web/src/router/private/Layout/partner.tsx
  apps/web/src/router/private/lazy-pages/index.ts
  apps/web/src/router/private/routes-partner.tsx
  packages/langs/en/navbar.json
  packages/langs/es/navbar.json
Labels: feature

#52 Feat: added views for getting all available products and checkout PSA-192 PSA-193
  apps/mobile/app.json
  apps/mobile/eas.json
  apps/mobile/package.json
  apps/mobile/src/app/(main)/(tabs)/training/__tests__/__snapshots__/_layout.spec.tsx.snap
  apps/mobile/src/app/(main)/(tabs)/training/__tests__/__snapshots__/servicesAndProducts.spec.tsx.snap
  apps/mobile/src/app/(main)/(tabs)/training/__tests__/__snapshots__/servicesAndProductsCheckout.spec.tsx.snap
  apps/mobile/src/app/(main)/(tabs)/training/__tests__/_layout.spec.tsx
  apps/mobile/src/app/(main)/(tabs)/training/__tests__/servicesAndProducts.spec.tsx
  apps/mobile/src/app/(main)/(tabs)/training/__tests__/servicesAndProductsCheckout.spec.tsx
  apps/mobile/src/app/(main)/(tabs)/training/_layout.tsx
  apps/mobile/src/app/(main)/(tabs)/training/index.tsx
  apps/mobile/src/app/(main)/(tabs)/training/servicesAndProducts.tsx
  apps/mobile/src/app/(main)/(tabs)/training/servicesAndProductsCheckout.tsx
  apps/mobile/src/app/(main)/__tests__/_layout.spec.tsx
  apps/mobile/src/app/(main)/_layout.tsx
  apps/mobile/src/components/KeyboardAvoidingDialog.tsx
  apps/mobile/src/components/Pagination.tsx
  apps/mobile/src/components/ProductServiceCard.tsx
  apps/mobile/src/components/SquaredButton.tsx
  apps/mobile/src/components/__tests__/KeyboardAvoidingDialog.spec.tsx
  apps/mobile/src/components/__tests__/Pagination.spec.tsx
  apps/mobile/src/components/__tests__/ProductServiceCard.spec.tsx
  apps/mobile/src/components/__tests__/__snapshots__/KeyboardAvoidingDialog.spec.tsx.snap
  apps/mobile/src/components/__tests__/__snapshots__/Pagination.spec.tsx.snap
  apps/mobile/src/components/__tests__/__snapshots__/ProductServiceCard.spec.tsx.snap
  apps/mobile/src/config/test/__mocks__/expo-router/index.tsx
  apps/mobile/src/config/test/jest.setup.ts
  apps/mobile/src/hooks/__tests__/useDebounce.spec.tsx
  apps/mobile/src/hooks/useDebounce.ts
  package.json
  packages/langs/en/index.ts
  packages/langs/en/productService.json
  packages/langs/en/training.json
  packages/langs/es/index.ts
  packages/langs/es/productService.json
  packages/langs/es/training.json
  packages/sportapp-repository/src/businessPartner/__tests__/index.spec.ts
  packages/sportapp-repository/src/businessPartner/endpoints/index.ts
  packages/sportapp-repository/src/businessPartner/index.ts
  packages/sportapp-repository/src/businessPartner/interfaces/index.ts
  packages/stores/src/alert/__tests__/index.spec.ts
  packages/stores/src/alert/index.ts
  packages/stores/src/alert/interfaces/index.ts
  packages/stores/src/businessPartner/__tests__/index.spec.ts
  packages/stores/src/businessPartner/index.ts
  packages/stores/src/businessPartner/interfaces/index.ts
  packages/stores/src/index.ts
  yarn.lock
Labels: feature

#55 Feature: PSA-185 update store and routes in partner
  apps/web/config/test/jest.setup.ts
  apps/web/package.json
  packages/langs/en/form.json
  packages/langs/es/form.json
  packages/sportapp-repository/src/business-partner/__tests__/index.spec.ts
  packages/sportapp-repository/src/business-partner/endpoints/__tests__/index.spec.ts
  packages/sportapp-repository/src/business-partner/endpoints/index.ts
  packages/sportapp-repository/src/business-partner/index.ts
  packages/sportapp-repository/src/business-partner/interfaces/api/product-create.ts
  packages/sportapp-repository/src/business-partner/interfaces/api/product-delete.ts
  packages/sportapp-repository/src/business-partner/interfaces/api/product.ts
  packages/stores/src/__tests__/index.spec.ts
  packages/stores/src/index.ts
  packages/stores/src/partner/products/__tests__/index.spec.ts
  packages/stores/src/partner/products/index.ts
  packages/stores/src/partner/products/interfaces/index.ts
  yarn.lock
Labels: feature

#56 Feature: PSA-185 add create product page
  apps/web/src/components/InputFileDrop/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/components/InputFileDrop/__tests__/index.spec.tsx
  apps/web/src/components/InputFileDrop/index.tsx
  apps/web/src/components/InputFileDrop/interfaces/index.ts
  apps/web/src/components/InputMarckDown/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/components/InputMarckDown/__tests__/index.spec.tsx
  apps/web/src/components/InputMarckDown/index.tsx
  apps/web/src/components/InputMarckDown/interfaces/index.ts
  apps/web/src/components/Inputs/FileUploadController/__test__/index.spec.tsx
  apps/web/src/components/Inputs/FileUploadController/index.tsx
  apps/web/src/components/Inputs/FileUploadController/interfaces/index.ts
  apps/web/src/components/Inputs/MarckDownController/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/components/Inputs/MarckDownController/__tests__/index.spec.tsx
  apps/web/src/components/Inputs/MarckDownController/index.tsx
  apps/web/src/components/Inputs/MarckDownController/interfaces/index.ts
  apps/web/src/containers/Partner/CreateProduct/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/containers/Partner/CreateProduct/__tests__/index.spec.tsx
  apps/web/src/containers/Partner/CreateProduct/_index.scss
  apps/web/src/containers/Partner/CreateProduct/index.tsx
  apps/web/src/containers/Partner/CreateProduct/interfaces/index.ts
  apps/web/src/containers/Partner/CreateProduct/utils/__tests__/index.spec.ts
  apps/web/src/containers/Partner/CreateProduct/utils/schema.ts
  apps/web/src/pages/Partner/CreateProduct/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/Partner/CreateProduct/__tests__/index.spec.tsx
  apps/web/src/pages/Partner/CreateProduct/index.tsx
  apps/web/src/utils/__tests__/files.spec.ts
  apps/web/src/utils/files.ts
  packages/langs/en/form.json
  packages/langs/es/form.json
  packages/sportapp-repository/src/business-partner/interfaces/api/product-create.ts
Labels: feature

#57 Feature: PSA-187 add obtain podructs in home page
  apps/web/src/pages/Partner/CreateProduct/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/Partner/CreateProduct/index.tsx
  apps/web/src/pages/Partner/Home/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/Partner/Home/__tests__/index.spec.tsx
  apps/web/src/pages/Partner/Home/index.tsx
  packages/langs/en/en.json
  packages/langs/en/index.ts
  packages/langs/en/productCreate.json
  packages/langs/en/productObtain.json
  packages/langs/es/es.json
  packages/langs/es/index.ts
  packages/langs/es/productCreate.json
  packages/langs/es/productObtain.json
Labels: feature

#58 Feature: PSA-194 add delete poducts in update page
  apps/web/src/pages/Partner/Home/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/Partner/Home/__tests__/index.spec.tsx
  apps/web/src/pages/Partner/Home/index.tsx
  apps/web/src/pages/Partner/UpdateProduct/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/Partner/UpdateProduct/__tests__/index.spec.tsx
  apps/web/src/pages/Partner/UpdateProduct/index.tsx
  apps/web/src/router/private/lazy-pages/index.ts
  apps/web/src/router/private/routes-partner.tsx
  packages/langs/en/index.ts
  packages/langs/en/productObtain.json
  packages/langs/en/productUpdate.json
  packages/langs/es/index.ts
  packages/langs/es/productObtain.json
  packages/langs/es/productUpdate.json
Labels: feature

#59 Feature: PSA-183 create payment plans view
  apps/web/src/containers/PaymentPlans/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/containers/PaymentPlans/__tests__/index.spec.tsx
  apps/web/src/containers/PaymentPlans/_index.scss
  apps/web/src/containers/PaymentPlans/components/CardPaymentPlan/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/containers/PaymentPlans/components/CardPaymentPlan/__tests__/index.spec.tsx
  apps/web/src/containers/PaymentPlans/components/CardPaymentPlan/index.tsx
  apps/web/src/containers/PaymentPlans/components/CardPaymentPlan/interfaces/index.ts
  apps/web/src/containers/PaymentPlans/index.tsx
  apps/web/src/containers/PaymentPlans/interfaces/index.ts
  apps/web/src/pages/User/Home/index.tsx
  packages/langs/en/index.ts
  packages/langs/en/paymentPlans.json
  packages/langs/es/form.json
  packages/langs/es/index.ts
  packages/langs/es/paymentPlans.json
Labels: feature

#60 Feature: PSA-197 PSA-198 add training plan based on user sport profile
  apps/mobile/sonar-project.properties
  apps/mobile/src/app/(main)/(tabs)/training/__tests__/__snapshots__/sportSessionHistory.spec.tsx.snap
  apps/mobile/src/app/(main)/(tabs)/training/__tests__/sportSessionHistory.spec.tsx
  apps/mobile/src/app/(main)/(tabs)/training/sportSessionHistory.tsx
  apps/mobile/src/app/(main)/(tabs)/training/sportSessionSummary.tsx
  apps/mobile/src/components/TrainingCard.tsx
  apps/mobile/src/components/__tests__/TrainingCard.spec.tsx
  apps/mobile/src/components/__tests__/__snapshots__/TrainingCard.spec.tsx.snap
  apps/mobile/src/config/test/__mocks__/dayjs/index.ts
  apps/web/config/lang/form.ts
  apps/web/config/test/jest.setup.ts
  apps/web/src/components/Inputs/DaysOfTheWeekController/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/components/Inputs/DaysOfTheWeekController/__tests__/index.spec.tsx
  apps/web/src/components/Inputs/DaysOfTheWeekController/index.tsx
  apps/web/src/components/Inputs/DaysOfTheWeekController/interfaces/index.tsx
  apps/web/src/components/Inputs/TimePickerController/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/components/Inputs/TimePickerController/__tests__/index.spec.tsx
  apps/web/src/components/Inputs/TimePickerController/index.tsx
  apps/web/src/components/Inputs/TimePickerController/interfaces/index.ts
  apps/web/src/containers/SportDataForm/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/containers/SportDataForm/__tests__/index.spec.tsx
  apps/web/src/containers/SportDataForm/index.tsx
  apps/web/src/containers/SportDataForm/utils/schema.ts
  apps/web/src/pages/User/Home/__tests__/index.spec.tsx
  apps/web/src/pages/User/Home/index.tsx
  apps/web/src/router/private/Layout/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/router/private/Layout/index.tsx
  packages/langs/en/form.json
  packages/langs/en/training.json
  packages/langs/en/validations.json
  packages/langs/es/form.json
  packages/langs/es/training.json
  packages/langs/es/validations.json
  packages/sportapp-repository/src/trainingPlan/__tests__/index.spec.ts
  packages/sportapp-repository/src/trainingPlan/endpoints/index.ts
  packages/sportapp-repository/src/trainingPlan/index.ts
  packages/sportapp-repository/src/trainingPlan/interfaces/index.ts
  packages/sportapp-repository/src/user/__tests__/index.spec.ts
  packages/sportapp-repository/src/user/interfaces/api/sportProfile.ts
  packages/stores/src/index.ts
  packages/stores/src/trainingPlan/__tests__/index.spec.ts
  packages/stores/src/trainingPlan/index.ts
  packages/stores/src/trainingPlan/interfaces/index.ts
  packages/stores/src/user/__tests__/index.spec.ts
Labels: feature

#61 Feature: PSA-48 sport session motivational alerts
  apps/mobile/src/app/(main)/(tabs)/training/__tests__/__snapshots__/sportSession.spec.tsx.snap
  apps/mobile/src/app/(main)/(tabs)/training/__tests__/sportSession.spec.tsx
  apps/mobile/src/app/(main)/(tabs)/training/sportSession.tsx
  apps/mobile/src/config/test/__mocks__/dayjs/index.ts
  packages/langs/en/index.ts
  packages/langs/en/motivation.json
  packages/langs/es/index.ts
  packages/langs/es/motivation.json
Labels: feature

#63 Feature: PSA-199 update products in partner
  apps/web/src/containers/Partner/CreateProduct/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/containers/Partner/CreateProduct/index.tsx
  apps/web/src/containers/Partner/CreateProduct/interfaces/index.ts
  apps/web/src/containers/Partner/CreateProduct/utils/schema.ts
  apps/web/src/pages/Partner/Home/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/Partner/Home/__tests__/index.spec.tsx
  apps/web/src/pages/Partner/Home/index.tsx
  apps/web/src/pages/Partner/Register/index.tsx
  apps/web/src/pages/Partner/UpdateProduct/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/Partner/UpdateProduct/__tests__/index.spec.tsx
  apps/web/src/pages/Partner/UpdateProduct/index.tsx
  packages/langs/es/productUpdate.json
  packages/sportapp-repository/src/business-partner/__tests__/index.spec.ts
  packages/sportapp-repository/src/business-partner/index.ts
  packages/sportapp-repository/src/business-partner/interfaces/api/product-update.ts
  packages/sportapp-repository/src/business-partner/interfaces/api/product.ts
  packages/stores/src/partner/products/__tests__/index.spec.ts
  packages/stores/src/partner/products/index.ts
  packages/stores/src/partner/products/interfaces/index.ts
Labels: feature

#64 Feature: PSA-202 add content in page show products obtained
  apps/web/src/components/Table/Pagination/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/components/Table/Pagination/__tests__/index.spec.tsx
  apps/web/src/components/Table/Pagination/index.tsx
  apps/web/src/components/Table/Pagination/interfaces/index.ts
  apps/web/src/pages/Partner/PurchasedProduct/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/Partner/PurchasedProduct/__tests__/index.spec.tsx
  apps/web/src/pages/Partner/PurchasedProduct/containers/Table/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/Partner/PurchasedProduct/containers/Table/__tests__/index.spec.tsx
  apps/web/src/pages/Partner/PurchasedProduct/containers/Table/index.tsx
  apps/web/src/pages/Partner/PurchasedProduct/containers/Table/interfaces/index.ts
  apps/web/src/pages/Partner/PurchasedProduct/containers/Table/utils/__tests__/index.spec.ts
  apps/web/src/pages/Partner/PurchasedProduct/containers/Table/utils/index.ts
  apps/web/src/pages/Partner/PurchasedProduct/index.tsx
  apps/web/src/router/private/lazy-pages/index.ts
  packages/langs/en/index.ts
  packages/langs/en/paymentPurchased.json
  packages/langs/es/index.ts
  packages/langs/es/paymentPurchased.json
  packages/sportapp-repository/src/business-partner/__tests__/index.spec.ts
  packages/sportapp-repository/src/business-partner/endpoints/__tests__/index.spec.ts
  packages/sportapp-repository/src/business-partner/endpoints/index.ts
  packages/sportapp-repository/src/business-partner/index.ts
  packages/sportapp-repository/src/business-partner/interfaces/api/product-purchased.ts
  packages/stores/src/partner/products/__tests__/index.spec.ts
  packages/stores/src/partner/products/index.ts
  packages/stores/src/partner/products/interfaces/index.ts
Labels: feature

#62 Feature: PSA-201 added payment checkout service
  apps/mobile/sonar-project.properties
  apps/mobile/src/app/(main)/(tabs)/training/__tests__/servicesAndProductsCheckout.spec.tsx
  apps/mobile/src/app/(main)/(tabs)/training/servicesAndProductsCheckout.tsx
  apps/mobile/src/app/(main)/__tests__/_layout.spec.tsx
  apps/mobile/src/app/(main)/_layout.tsx
  packages/sportapp-repository/src/businessPartner/__tests__/index.spec.ts
  packages/sportapp-repository/src/businessPartner/endpoints/index.ts
  packages/sportapp-repository/src/businessPartner/index.ts
  packages/sportapp-repository/src/businessPartner/interfaces/index.ts
  packages/stores/src/businessPartner/__tests__/index.spec.ts
  packages/stores/src/businessPartner/index.ts
  packages/stores/src/businessPartner/interfaces/index.ts
Labels: feature

#65 Feature: PSA-183 add payment form
  apps/web/package.json
  apps/web/src/components/Inputs/TexFieldController/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/components/Inputs/TexFieldController/__tests__/index.spec.tsx
  apps/web/src/components/Inputs/TexFieldController/index.tsx
  apps/web/src/components/Inputs/TexFieldController/interfaces/index.ts
  apps/web/src/components/Inputs/TexFieldController/utils/__tests__/index.spec.ts
  apps/web/src/components/Inputs/TexFieldController/utils/index.ts
  apps/web/src/containers/PaymentForm/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/containers/PaymentForm/__tests__/index.spec.tsx
  apps/web/src/containers/PaymentForm/index.tsx
  apps/web/src/containers/PaymentForm/interfaces/index.ts
  apps/web/src/containers/PaymentForm/utils/__tests__/index.spec.ts
  apps/web/src/containers/PaymentForm/utils/__tests__/schema.spec.ts
  apps/web/src/containers/PaymentForm/utils/index.ts
  apps/web/src/containers/PaymentForm/utils/schema.ts
  packages/langs/en/form.json
  packages/langs/es/form.json
  yarn.lock
Labels: feature

#66 Feature: PSA-183 add integration with appi in payment plan
  apps/web/src/containers/PaymentForm/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/containers/PaymentForm/__tests__/index.spec.tsx
  apps/web/src/containers/PaymentForm/index.tsx
  apps/web/src/containers/PaymentForm/interfaces/index.ts
  apps/web/src/containers/PaymentForm/utils/schema.ts
  apps/web/src/containers/PaymentPlans/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/containers/PaymentPlans/__tests__/index.spec.tsx
  apps/web/src/containers/PaymentPlans/container/ModalStep/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/containers/PaymentPlans/container/ModalStep/__tests__/index.spec.tsx
  apps/web/src/containers/PaymentPlans/container/ModalStep/index.tsx
  apps/web/src/containers/PaymentPlans/container/ModalStep/interfaces/index.ts
  apps/web/src/containers/PaymentPlans/index.tsx
  apps/web/src/containers/PaymentPlans/interfaces/index.ts
  apps/web/src/pages/User/Home/index.tsx
  packages/langs/en/form.json
  packages/langs/en/paymentPlans.json
  packages/langs/es/form.json
  packages/langs/es/paymentPlans.json
  packages/sportapp-repository/src/user/__tests__/index.spec.ts
  packages/sportapp-repository/src/user/endpoints/__tests__/index.spec.ts
  packages/sportapp-repository/src/user/endpoints/index.ts
  packages/sportapp-repository/src/user/index.ts
  packages/sportapp-repository/src/user/interfaces/api/personalProfile.ts
  packages/sportapp-repository/src/user/interfaces/api/updatePlan.ts
  packages/stores/src/__tests__/index.spec.ts
  packages/stores/src/businessPartner/__tests__/index.spec.ts
  packages/stores/src/index.ts
  packages/stores/src/paymentPlan/__tests__/indes.spec.ts
  packages/stores/src/paymentPlan/index.ts
  packages/stores/src/paymentPlan/interfaces/index.ts
  packages/stores/src/sport/__tests__/index.spec.ts
  packages/stores/src/trainingPlan/__tests__/index.spec.ts
  packages/stores/src/user/__tests__/index.spec.ts
  packages/stores/src/user/interfaces/index.ts
Labels: refactor, feature

#68 BugFix: correction navbar view and premisions
  apps/web/src/components/ContainerLayout/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/components/ContainerLayout/__tests__/index.spec.tsx
  apps/web/src/components/Navbar/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/components/Navbar/__tests__/index.spec.tsx
  apps/web/src/components/Navbar/_index.scss
  apps/web/src/components/Navbar/index.tsx
  apps/web/src/containers/PaymentPlans/__tests__/index.spec.tsx
  apps/web/src/containers/PaymentPlans/index.tsx
  apps/web/src/containers/PersonalDataForm/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/containers/PersonalDataForm/index.tsx
  apps/web/src/pages/User/Config/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/User/Config/__tests__/index.spec.tsx
  apps/web/src/pages/User/Home/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/User/Home/__tests__/index.spec.tsx
  apps/web/src/pages/User/Preference/CardSelection/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/User/Preference/Form/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/User/Preference/List/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/User/Preference/__tests__/__snapshots__/index.spec.tsx.snap
Labels: bugfix

#69 BugFix: correction time format
  apps/web/src/components/Inputs/TimePickerController/index.tsx
Labels: bugfix

#70 Bugfix: premium appointments wrong type
  apps/web/src/components/Navbar/index.tsx
  apps/web/src/pages/User/Preference/CardSelection/__tests__/index.spec.tsx
  apps/web/src/pages/User/Preference/CardSelection/index.tsx
  apps/web/src/pages/User/Preference/Form/__tests__/index.spec.tsx
  apps/web/src/pages/User/Preference/Form/index.tsx
  apps/web/src/pages/User/Preference/List/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/User/Preference/List/__tests__/index.spec.tsx
  apps/web/src/pages/User/Preference/List/index.tsx
  apps/web/src/pages/User/Preference/__tests__/index.spec.tsx
  apps/web/src/pages/User/Preference/index.tsx
  apps/web/src/router/private/lazy-pages/index.ts
  apps/web/src/router/private/routes.tsx
Labels: bugfix

#72 Fix: fix errors with mobile app in android
  apps/mobile/app.json
  apps/mobile/package.json
  apps/mobile/src/components/KeyboardAvoidingDialog.tsx
  packages/sportapp-repository/src/trainingPlan/endpoints/index.ts
Labels: bugfix
