Repository Miso-Code/sportapp-front, pull requests merged in 2024-05, with the labels that each got.

#73 Feature: add e2e init config
  apps/web/.gitignore
  apps/web/e2e/user/flows/update-profile.spec.ts
  apps/web/e2e/user/objects/login/index.ts
  apps/web/e2e/user/objects/register/index.ts
  apps/web/e2e/user/objects/register/interfaces/index.ts
  apps/web/jest.config.ts
  apps/web/package.json
  apps/web/playwright.config.ts
  turbo.json
  yarn.lock
Labels: e2e

#75 Feature: PSA-69 Payment plan select mobile
  apps/mobile/src/app/(main)/(tabs)/__tests__/_layout.spec.tsx
  apps/mobile/src/app/(main)/(tabs)/_layout.tsx
  apps/mobile/src/app/(main)/(tabs)/profile/__tests__/__snapshots__/_layout.spec.tsx.snap
  apps/mobile/src/app/(main)/(tabs)/profile/__tests__/__snapshots__/paymentPlans.spec.tsx.snap
  apps/mobile/src/app/(main)/(tabs)/profile/__tests__/_layout.spec.tsx
  apps/mobile/src/app/(main)/(tabs)/profile/__tests__/index.spec.tsx
  apps/mobile/src/app/(main)/(tabs)/profile/__tests__/paymentPlans.spec.tsx
  apps/mobile/src/app/(main)/(tabs)/profile/_layout.tsx
  apps/mobile/src/app/(main)/(tabs)/profile/index.tsx
  apps/mobile/src/app/(main)/(tabs)/profile/paymentPlans.tsx
  apps/mobile/src/app/(main)/(tabs)/training/__tests__/_layout.spec.tsx
  apps/mobile/src/app/(main)/(tabs)/training/__tests__/index.spec.tsx
  apps/mobile/src/app/(main)/(tabs)/training/index.tsx
  apps/mobile/src/components/KeyboardAvoidingDialog.tsx
  packages/langs/en/paymentPlans.json
  packages/langs/es/paymentPlans.json
Labels: feature

#79 Feature: Add support for push notifications from FCM PSA-207
  apps/mobile/app.json
  apps/mobile/package.json
  apps/mobile/src/app/(main)/__tests__/_layout.spec.tsx
  apps/mobile/src/app/(main)/_layout.tsx
  apps/mobile/src/app/__tests__/login.spec.tsx
  apps/mobile/src/app/login.tsx
  apps/mobile/src/hooks/__tests__/usePushNotification.spec.tsx
  apps/mobile/src/hooks/usePushNotifications.ts
  packages/sportapp-repository/src/alerts/endpoints/index.ts
  packages/sportapp-repository/src/alerts/index.ts
  packages/sportapp-repository/src/alerts/interfaces/index.ts
  yarn.lock
Labels: feature

#81 Feature: PSA-76 add products page
  apps/web/package.json
  apps/web/src/components/Navbar/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/components/Navbar/__tests__/index.spec.tsx
  apps/web/src/components/Navbar/index.tsx
  apps/web/src/hooks/__tests__/useDebounce.spec.tsx
  apps/web/src/hooks/useDebounce.ts
  apps/web/src/pages/Partner/PurchasedProduct/containers/Table/utils/__tests__/index.spec.ts
  apps/web/src/pages/Partner/PurchasedProduct/containers/Table/utils/index.ts
  apps/web/src/pages/User/OtherServices/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/User/OtherServices/__tests__/index.spec.tsx
  apps/web/src/pages/User/OtherServices/_index.scss
  apps/web/src/pages/User/OtherServices/components/CardModalSelect/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/User/OtherServices/components/CardModalSelect/__tests__/index.spec.tsx
  apps/web/src/pages/User/OtherServices/components/CardModalSelect/index.tsx
  apps/web/src/pages/User/OtherServices/components/CardModalSelect/interfaces/index.ts
  apps/web/src/pages/User/OtherServices/index.tsx
  apps/web/src/router/private/lazy-pages/index.ts
  apps/web/src/router/private/routes.tsx
  packages/langs/en/index.ts
  packages/langs/en/otherService.json
  packages/langs/es/index.ts
  packages/langs/es/otherService.json
  yarn.lock
Labels: feature

#80 Feature: added sport events to mobile calendar PSA-205
  apps/mobile/app.json
  apps/mobile/package.json
  apps/mobile/src/app/(main)/(tabs)/training/__tests__/__snapshots__/sportSessionHistory.spec.tsx.snap
  apps/mobile/src/app/(main)/(tabs)/training/__tests__/sportSessionHistory.spec.tsx
  apps/mobile/src/app/(main)/(tabs)/training/sportSessionHistory.tsx
  apps/mobile/src/components/EventCard.tsx
  apps/mobile/src/components/__tests__/EventCard.spec.tsx
  apps/mobile/src/components/__tests__/__snapshots__/EventCard.spec.tsx.snap
  packages/sportapp-repository/src/sportEvent/__tests__/index.spec.ts
  packages/sportapp-repository/src/sportEvent/endpoints/index.ts
  packages/sportapp-repository/src/sportEvent/index.ts
  packages/sportapp-repository/src/sportEvent/interfaces/index.ts
  packages/stores/src/index.ts
  packages/stores/src/sportEvents/__tests__/index.spec.ts
  packages/stores/src/sportEvents/index.ts
  packages/stores/src/sportEvents/interfaces/index.ts
  yarn.lock
Labels: feature

#82 Feature: added sport events to mobile calendar PSA-205 (#80)
  apps/mobile/src/app/(main)/(tabs)/__tests__/__snapshots__/notifications.spec.tsx.snap
  apps/mobile/src/app/(main)/(tabs)/__tests__/notifications.spec.tsx
  apps/mobile/src/app/(main)/(tabs)/notifications.tsx
  apps/mobile/src/hooks/__tests__/usePushNotification.spec.tsx
  apps/mobile/src/hooks/usePushNotifications.ts
  packages/stores/src/alert/__tests__/index.spec.ts
  packages/stores/src/alert/index.ts
  packages/stores/src/alert/interfaces/index.ts
Labels: feature

#83 Feature: PSA-101 add products payment page
  apps/mobile/src/app/(main)/(tabs)/__tests__/__snapshots__/notifications.spec.tsx.snap
  apps/web/src/pages/User/OtherServices/Payment/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/User/OtherServices/Payment/__tests__/index.spec.tsx
  apps/web/src/pages/User/OtherServices/Payment/_index.scss
  apps/web/src/pages/User/OtherServices/Payment/index.tsx
  apps/web/src/pages/User/OtherServices/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/User/OtherServices/__tests__/index.spec.tsx
  apps/web/src/pages/User/OtherServices/components/CardModalSelect/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/User/OtherServices/components/CardModalSelect/__tests__/index.spec.tsx
  apps/web/src/pages/User/OtherServices/components/CardModalSelect/index.tsx
  apps/web/src/pages/User/OtherServices/components/CardModalSelect/interfaces/index.ts
  apps/web/src/pages/User/OtherServices/index.tsx
  apps/web/src/router/private/lazy-pages/index.ts
  apps/web/src/router/private/routes.tsx
  packages/stores/src/alert/__tests__/index.spec.ts
  packages/stores/src/alert/index.ts
  packages/stores/src/alert/interfaces/index.ts
  packages/stores/src/businessPartner/index.ts
  packages/stores/src/businessPartner/interfaces/index.ts
Labels: feature

#85 Feature: PSA-123 PSA-214 business partner product service suggestion and recovery alert
  apps/mobile/src/app/(main)/(tabs)/__tests__/__snapshots__/notifications.spec.tsx.snap
  apps/mobile/src/app/(main)/(tabs)/training/__tests__/__snapshots__/sportSessionHistory.spec.tsx.snap
  apps/mobile/src/app/(main)/(tabs)/training/__tests__/__snapshots__/sportSessionSummary.spec.tsx.snap
  apps/mobile/src/app/(main)/(tabs)/training/__tests__/sportSession.spec.tsx
  apps/mobile/src/app/(main)/(tabs)/training/__tests__/sportSessionHistory.spec.tsx
  apps/mobile/src/app/(main)/(tabs)/training/__tests__/sportSessionSummary.spec.tsx
  apps/mobile/src/app/(main)/(tabs)/training/sportSession.tsx
  apps/mobile/src/app/(main)/(tabs)/training/sportSessionHistory.tsx
  apps/mobile/src/app/(main)/(tabs)/training/sportSessionSummary.tsx
  apps/mobile/src/components/Kpi.tsx
  apps/mobile/src/components/ProductServiceCard.tsx
  apps/mobile/src/components/__tests__/__snapshots__/Kpi.spec.tsx.snap
  apps/mobile/src/components/__tests__/__snapshots__/ProductServiceCard.spec.tsx.snap
  packages/langs/en/productService.json
  packages/langs/en/session.json
  packages/langs/es/productService.json
  packages/langs/es/session.json
  packages/sportapp-repository/src/businessPartner/__tests__/index.spec.ts
  packages/sportapp-repository/src/businessPartner/endpoints/index.ts
  packages/sportapp-repository/src/businessPartner/index.ts
  packages/sportapp-repository/src/businessPartner/interfaces/index.ts
  packages/sportapp-repository/src/nutritionalPlan/__tests__/index.spec.ts
  packages/sportapp-repository/src/nutritionalPlan/endpoints/index.ts
  packages/sportapp-repository/src/nutritionalPlan/index.ts
  packages/sportapp-repository/src/nutritionalPlan/interfaces/index.ts
  packages/stores/src/businessPartner/__tests__/index.spec.ts
  packages/stores/src/businessPartner/index.ts
  packages/stores/src/businessPartner/interfaces/index.ts
  packages/stores/src/nutritionalPlan/__tests__/index.spec.ts
  packages/stores/src/nutritionalPlan/index.ts
  packages/stores/src/nutritionalPlan/interfaces/index.ts
  packages/stores/src/sportEvents/index.ts
Labels: feature

#86 Featureadd calendar to events and trainings
  apps/web/config/test/jest.setup.ts
  apps/web/jest.config.ts
  apps/web/package.json
  apps/web/src/components/Navbar/index.tsx
  apps/web/src/components/Navbar/interfaces/index.ts
  apps/web/src/hooks/__tests__/useLocation.spec.tsx
  apps/web/src/hooks/useLocation.ts
  apps/web/src/pages/User/Training/Calendar/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/User/Training/Calendar/__tests__/index.spec.tsx
  apps/web/src/pages/User/Training/Calendar/_index.scss
  apps/web/src/pages/User/Training/Calendar/components/InfoCards/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/User/Training/Calendar/components/InfoCards/__tests__/index.spec.tsx
  apps/web/src/pages/User/Training/Calendar/components/InfoCards/index.tsx
  apps/web/src/pages/User/Training/Calendar/components/InfoCards/interfaces/index.ts
  apps/web/src/pages/User/Training/Calendar/containers/CustomCalendar/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/User/Training/Calendar/containers/CustomCalendar/__tests__/index.spec.tsx
  apps/web/src/pages/User/Training/Calendar/containers/CustomCalendar/_index.scss
  apps/web/src/pages/User/Training/Calendar/containers/CustomCalendar/index.tsx
  apps/web/src/pages/User/Training/Calendar/containers/CustomCalendar/interfaces/index.ts
  apps/web/src/pages/User/Training/Calendar/containers/CustomCalendar/utils/__tests__/index.spec.tsx
  apps/web/src/pages/User/Training/Calendar/containers/CustomCalendar/utils/index.tsx
  apps/web/src/pages/User/Training/Calendar/containers/DialogEvent/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/User/Training/Calendar/containers/DialogEvent/__tests__/index.spec.tsx
  apps/web/src/pages/User/Training/Calendar/containers/DialogEvent/components/EventCard/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/User/Training/Calendar/containers/DialogEvent/components/EventCard/__tests__/index.spec.tsx
  apps/web/src/pages/User/Training/Calendar/containers/DialogEvent/components/EventCard/index.tsx
  apps/web/src/pages/User/Training/Calendar/containers/DialogEvent/components/TrainingCard/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/User/Training/Calendar/containers/DialogEvent/components/TrainingCard/__tests__/index.spec.tsx
  apps/web/src/pages/User/Training/Calendar/containers/DialogEvent/components/TrainingCard/index.tsx
  apps/web/src/pages/User/Training/Calendar/containers/DialogEvent/index.tsx
  apps/web/src/pages/User/Training/Calendar/containers/DialogEvent/interfaces/index.ts
  apps/web/src/pages/User/Training/Calendar/index.tsx
  apps/web/src/pages/User/Training/Calendar/utils/__tests__/index.spec.ts
  apps/web/src/pages/User/Training/Calendar/utils/index.ts
  apps/web/src/pages/User/Training/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/User/Training/__tests__/index.spec.tsx
  apps/web/src/pages/User/Training/_index.scss
  apps/web/src/pages/User/Training/index.tsx
  apps/web/src/router/private/lazy-pages/index.ts
  apps/web/src/router/private/routes.tsx
  packages/langs/en/training.json
  packages/langs/es/training.json
  yarn.lock
Labels: feature

#87 BugFix: correction texts PSA-41
  packages/langs/es/training.json
Labels: bugfix

#88 BugFix: improved performance, state refresh and fixed global theme issues
  apps/mobile/src/app/(main)/(tabs)/__tests__/__snapshots__/notifications.spec.tsx.snap
  apps/mobile/src/app/(main)/(tabs)/__tests__/__snapshots__/profile.spec.tsx.snap
  apps/mobile/src/app/(main)/(tabs)/_layout.tsx
  apps/mobile/src/app/(main)/(tabs)/profile/__tests__/index.spec.tsx
  apps/mobile/src/app/(main)/(tabs)/profile/__tests__/paymentPlans.spec.tsx
  apps/mobile/src/app/(main)/(tabs)/profile/__tests__/settings.spec.tsx
  apps/mobile/src/app/(main)/(tabs)/profile/index.tsx
  apps/mobile/src/app/(main)/(tabs)/profile/nutritionalProfile.tsx
  apps/mobile/src/app/(main)/(tabs)/profile/paymentPlans.tsx
  apps/mobile/src/app/(main)/(tabs)/profile/settings.tsx
  apps/mobile/src/app/(main)/(tabs)/profile/sportsProfile.tsx
  apps/mobile/src/app/(main)/(tabs)/training/sportSessionHistory.tsx
  apps/mobile/src/app/(main)/(tabs)/training/sportSessionSummary.tsx
  apps/mobile/src/app/(main)/_layout.tsx
  apps/mobile/src/app/__tests__/login.spec.tsx
  apps/mobile/src/app/login.tsx
  apps/mobile/src/components/DayOfTheWeekInput.tsx
  apps/mobile/src/components/ProductServiceCard.tsx
  apps/mobile/src/components/__tests__/__snapshots__/ProductServiceCard.spec.tsx.snap
  apps/mobile/src/config/theme.ts
  apps/mobile/src/hooks/usePushNotifications.ts
  packages/stores/src/auth/index.ts
  packages/stores/src/nutritionalPlan/index.ts
  packages/stores/src/partner/products/index.ts
  packages/stores/src/paymentPlan/index.ts
  packages/stores/src/sport/index.ts
  packages/stores/src/sportEvents/index.ts
  packages/stores/src/sportSession/index.ts
  packages/stores/src/user/index.ts
Labels: bugfix

#89 BugFix: correction styles, texts and payment config
  apps/web/config/lang/i18n.ts
  apps/web/src/pages/User/OtherServices/Payment/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/User/OtherServices/Payment/__tests__/index.spec.tsx
  apps/web/src/pages/User/OtherServices/Payment/index.tsx
  apps/web/src/pages/User/OtherServices/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/User/OtherServices/_index.scss
  apps/web/src/pages/User/OtherServices/components/CardModalSelect/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/User/OtherServices/components/CardModalSelect/index.tsx
  apps/web/src/pages/User/OtherServices/index.tsx
Labels: bugfix

#92 Feature: PSA-00 add new features to change lang and update products
  apps/mobile/src/app/(main)/(tabs)/__tests__/__snapshots__/notifications.spec.tsx.snap
  apps/web/src/components/NavbarTop/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/components/NavbarTop/__tests__/index.spec.tsx
  apps/web/src/components/NavbarTop/index.tsx
  apps/web/src/containers/ChangeLang/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/containers/ChangeLang/__tests__/index.spec.tsx
  apps/web/src/containers/ChangeLang/_index.scss
  apps/web/src/containers/ChangeLang/index.tsx
  apps/web/src/containers/ChangeLang/utils/__tests__/index.spec.ts
  apps/web/src/containers/ChangeLang/utils/schema.ts
  apps/web/src/containers/Partner/CreateProduct/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/containers/Partner/CreateProduct/index.tsx
  apps/web/src/containers/Partner/CreateProduct/utils/__tests__/index.spec.ts
  apps/web/src/containers/Partner/CreateProduct/utils/schema.ts
  apps/web/src/pages/Partner/CreateProduct/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/Partner/Home/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/Partner/Lang/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/Partner/Lang/__tests__/index.spec.tsx
  apps/web/src/pages/Partner/Lang/index.tsx
  apps/web/src/pages/Partner/PurchasedProduct/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/Partner/UpdateProduct/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/Partner/UpdateProduct/__tests__/index.spec.tsx
  apps/web/src/pages/Partner/UpdateProduct/index.tsx
  apps/web/src/pages/User/Config/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/User/Config/components/Menu/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/User/Config/components/Menu/index.tsx
  apps/web/src/pages/User/Config/index.tsx
  apps/web/src/router/index.tsx
  apps/web/src/router/private/__tests__/partner.spec.tsx
  apps/web/src/router/private/lazy-pages/index.ts
  apps/web/src/router/private/routes-partner.tsx
  packages/langs/en/config.json
  packages/langs/en/form.json
  packages/langs/en/navbar.json
  packages/langs/es/config.json
  packages/langs/es/form.json
  packages/langs/es/navbar.json
  packages/sportapp-repository/src/business-partner/interfaces/api/product.ts
  packages/stores/src/__tests__/index.spec.ts
  packages/stores/src/index.ts
  packages/stores/src/lang/__tests__/index.spec.ts
  packages/stores/src/lang/index.ts
  packages/stores/src/lang/interfaces/index.ts
  packages/stores/src/partner/auth/index.ts
Labels: refactor, feature

#95 Feature: PSA-00 add e2e test from create product
  apps/mobile/src/app/(main)/(tabs)/__tests__/__snapshots__/notifications.spec.tsx.snap
  apps/mobile/src/app/(main)/(tabs)/__tests__/notifications.spec.tsx
  apps/web/.gitignore
  apps/web/config/lang/form.ts
  apps/web/e2e/exports/README.md
  apps/web/e2e/partner/flows/01-register-profile.spec.ts
  apps/web/e2e/partner/flows/03-products.spec.ts
  apps/web/e2e/partner/flows/register-profile.spec.ts
  apps/web/e2e/partner/objects/create-product/index.ts
  apps/web/e2e/partner/objects/create-product/interface/index.ts
  apps/web/e2e/partner/utils/interfaces/index.ts
  apps/web/e2e/partner/utils/partner.ts
  apps/web/e2e/user/flows/02-register-profile.spec.ts
  apps/web/e2e/user/flows/03-plan-profile.spec.ts
  apps/web/e2e/user/flows/04-other-service.spec.ts
  apps/web/e2e/user/objects/home/interface/index.ts
  apps/web/e2e/user/objects/home/plan-data.ts
  apps/web/e2e/user/objects/otherService/index.ts
  apps/web/e2e/user/utils/interfaces/index.ts
  apps/web/e2e/user/utils/user.ts
  apps/web/e2e/utils/index.ts
  apps/web/src/containers/PaymentPlans/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/containers/PaymentPlans/index.tsx
  apps/web/src/pages/Partner/CreateProduct/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/Partner/CreateProduct/_index.scss
  apps/web/src/pages/Partner/CreateProduct/index.tsx
  apps/web/src/pages/Partner/Login/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/Partner/Login/index.tsx
  apps/web/src/pages/Partner/UpdateProduct/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/Partner/UpdateProduct/_index.scss
  apps/web/src/pages/Partner/UpdateProduct/index.tsx
  apps/web/src/pages/User/Home/index.tsx
  apps/web/src/pages/User/Login/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/User/Login/_index.scss
  apps/web/src/pages/User/Login/index.tsx
  apps/web/src/pages/User/OtherServices/__tests__/__snapshots__/index.spec.tsx.snap
  apps/web/src/pages/User/OtherServices/index.tsx
  packages/langs/en/errors.json
  packages/langs/en/login.json
  packages/langs/es/errors.json
  packages/langs/es/login.json
  packages/sportapp-repository/src/business-partner/__tests__/index.spec.ts
  packages/sportapp-repository/src/business-partner/interfaces/api/product-create.ts
  packages/stores/src/partner/products/__tests__/index.spec.ts
Labels: e2e

#94 Feature: PSA-219 Caloric intake notifications (intake monitoring) for premium plan
  apps/mobile/src/app/(main)/(tabs)/training/__tests__/sportSession.spec.tsx
  apps/mobile/src/app/(main)/(tabs)/training/sportSession.tsx
  apps/mobile/src/app/(main)/__tests__/_layout.spec.tsx
  apps/mobile/src/app/(main)/_layout.tsx
Labels: feature

#96 Feature: Update e2e config and validations
  .github/workflows/create-release.yml
  apps/web/e2e/partner/flows/03-products.spec.ts
  apps/web/e2e/user/flows/05-plan-profile.spec.ts
  apps/web/e2e/user/objects/home/nutritional-data.ts
  apps/web/playwright.config.ts
Labels: e2e

#93 Test: added e2e cases on mobile
  apps/mobile/.detoxrc.js
  apps/mobile/.gitignore
  apps/mobile/App.tsx
  apps/mobile/app.json
  apps/mobile/e2e/jest.config.js
  apps/mobile/e2e/profile.test.ts
  apps/mobile/e2e/screens/bottomNav.ts
  apps/mobile/e2e/screens/index.ts
  apps/mobile/e2e/screens/login.ts
  apps/mobile/e2e/screens/nutritionalData.ts
  apps/mobile/e2e/screens/nutritionalPlan.ts
  apps/mobile/e2e/screens/paymentPlan.ts
  apps/mobile/e2e/screens/personalData.ts
  apps/mobile/e2e/screens/profile.ts
  apps/mobile/e2e/screens/servicesAndProducts.ts
  apps/mobile/e2e/screens/servicesAndProductsCheckout.ts
  apps/mobile/e2e/screens/settings.ts
  apps/mobile/e2e/screens/sportsData.ts
  apps/mobile/e2e/screens/training.ts
  apps/mobile/e2e/screens/trainingCalendar.ts
  apps/mobile/e2e/screens/trainingSession.ts
  apps/mobile/e2e/screens/trainingSessionSummary.ts
  apps/mobile/e2e/servicesAndProducts.test.ts
  apps/mobile/e2e/training.test.ts
  apps/mobile/e2e/utils/api.ts
  apps/mobile/e2e/utils/generators.ts
  apps/mobile/e2e/utils/interfaces.ts
  apps/mobile/e2e/utils/maps.ts
  apps/mobile/e2e/utils/search.ts
  apps/mobile/jest.config.ts
  apps/mobile/package.json
  apps/mobile/src/app/(main)/(tabs)/_layout.tsx
  apps/mobile/src/app/(main)/(tabs)/profile/__tests__/__snapshots__/paymentPlans.spec.tsx.snap
  apps/mobile/src/app/(main)/(tabs)/profile/paymentPlans.tsx
  apps/mobile/src/app/(main)/(tabs)/profile/sportsProfile.tsx
  apps/mobile/src/app/(main)/(tabs)/training/__tests__/servicesAndProducts.spec.tsx
  apps/mobile/src/app/(main)/(tabs)/training/servicesAndProducts.tsx
  apps/mobile/src/components/Dropdown.tsx
  apps/mobile/src/components/ProductServiceCard.tsx
  apps/mobile/src/components/TimePicker.tsx
  apps/mobile/src/components/TimerRing.tsx
  apps/mobile/src/components/__tests__/__snapshots__/Dropdown.spec.tsx.snap
  apps/mobile/src/components/__tests__/__snapshots__/ProductServiceCard.spec.tsx.snap
  apps/mobile/src/components/__tests__/__snapshots__/TimeRing.spec.tsx.snap
  packages/sportapp-repository/src/business-partner/index.ts
  yarn.lock
Labels: e2e

#98 HotFix: Correction send to session training
  apps/web/src/pages/User/Training/Calendar/index.tsx
Labels: bugfix
